Algoritmo "verificando intervalo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/05/2023
Var
numero: inteiro

Inicio
escreva("Digite um número: ")
   leia(numero)

   se (numero) >= 100 e (numero) <= 200
    entao
      escreva("O número está no intervalo entre 100 e 200.")
   senao
      escreva("O número está fora do intervalo entre 100 e 200.")
   fimse

Fimalgoritmo