Algoritmo "verificando idade"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/05/2023
Var
nome: caractere
   idade: inteiro
Inicio
escreva("Digite o nome: ")
   leia(nome)

   escreva("Digite a idade: ")
   leia(idade)

   se idade >= 18 então
      escreva("Olá, ", nome, "! Você é maior de idade.")
   senao
      escreva("Olá, ", nome, "! Você é menor de idade.")
   fimse
Fimalgorítimo